=== ramonmeza/conversation_editor/data/conversation_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "default": {},
    "title": "The schema for a Conversation.",
    "required": [
        "name",
        "description",
        "nodes",
        "connections"
    ],
    "properties": {
        "name": {
            "type": "string",
            "default": "New Conversation",
            "title": "Name of the conversation.",
            "examples": [
                "Introduction to Helen",
                "Bar Fight Scene",
                "Shopkeep Interaction"
            ]
        },
        "description": {
            "type": "string",
            "default": "This is the description of the conversation.",
            "title": "High-level description of the conversation.",
            "examples": [
                "When the player first interacts with Helen",
                "Just before a bar fight breaks out, the player has a chance to deescalate the situation.",
                "The dialogue to be used when interacting with the shopkeeper"
            ]
        },
        "nodes": {
            "type": "array",
            "default": [],
            "title": "The nodes used during this conversation.",
            "items": {
                "oneOf": [{
                    "talk_node": {
                        "type": "object",
                        "title": "Contains all data related to a single node of conversation.",
                        "required": [
                            "speaker",
                            "text"
                        ],
                        "properties": {
                            "speaker": {
                                "type": "string",
                                "title": "Name of the speaker.",
                                "examples": [
                                    "Helen",
                                    "Player",
                                    "Bar Patron 1",
                                    "Bar Patron 2",
                                    "Shopkeep"
                                ]
                            },
                            "text": {
                                "type": "string",
                                "title": "Dialogue to be spoken.",
                                "examples": [
                                    "Hey there, how can I help you?",
                                    "I'm not feeling too great. Can you take a look at me?",
                                    "Doesn't seem like you have any wounds on you. What are your symptoms?",
                                    "Well here's your problem! You're missing a leg!"
                                ]
                            }
                        }
                    }
                }, {
                    "attribute_comparison_node": {
                        "type": "object",
                        "title": "",
                        "required": [
                            "operator",
                            "attribute",
                            "value"
                        ],
                        "properties": {
                            "operator": {
                                "type": "string",
                                "default": "==",
                                "title": "Comparison operator to be used.",
                                "examples": [
                                    "==",
                                    "!=",
                                    "<",
                                    "<=",
                                    ">",
                                    ">="
                                ]
                            },
                            "attribute": {
                                "type": "string",
                                "title": "Name of the attribute to compare the value against.",
                                "examples": [
                                    "Health",
                                    "Influence",
                                    "Trustworthiness"
                                ]
                            },
                            "value": {
                                "type": ["integer", "string"],
                                "title": "The value to compare the attribute against.",
                                "examples": [
                                    100,
                                    "SomeString"
                                ]
                            }
                        }
                    }
                }]
            },
            "examples": [
                [{
                    "speaker": "Doctor",
                    "text": "Hey there, how can I help you?"
                },
                {
                    "speaker": "Player",
                    "text": "I'm not feeling too great. Can you take a look at me?"
                },
                {
                    "operator": "==",
                    "attribute": "Health",
                    "value": 100
                },
                {
                    "speaker": "Doctor",
                    "text": "Doesn't seem like you have any wounds on you. What are your symptoms?"
                },
                {
                    "speaker": "Doctor",
                    "text": "Well here's your problem! You're missing a leg!"
                }]
            ]
        },
        "connections": {
            "type": "array",
            "default": [],
            "title": "Defines the connections between nodes. Each element of the array corresponds to the node at the same index in the nodes property. Each element contains a list of outgoing connections to indices within the nodes array.",
            "items": {
                "type": "array",
                "title": "Array of connections.",
                "items": {
                    "type": "integer",
                    "title": "List of node indices of nodes to connect to, obtained from the corresponding nodes' index in the nodes property.",
                    "examples": [
                        1,
                        2,
                        3,
                        4
                    ]
                },
                "examples": [
                    [1],
                    [2],
                    [3, 4],
                    [],
                    []
                ]
            },
            "examples": [
                [
                    [1],
                    [2],
                    [3,4],
                    [],
                    []
                ]
            ]
        }
    },
    "examples": [{
        "name": "Conversation Name",
        "description": "Description of the conversation",
        "nodes": [{
            "speaker": "Doctor",
            "text": "Hey there, how can I help you?"
        },
        {
            "speaker": "Player",
            "text": "I'm not feeling too great. Can you take a look at me?"
        },
        {
            "operator": "==",
            "attribute": "Health",
            "value": 100
        },
        {
            "speaker": "Doctor",
            "text": "Doesn't seem like you have any wounds on you. What are your symptoms?"
        },
        {
            "speaker": "Doctor",
            "text": "Well here's your problem! You're missing a leg!"
        }],
        "connections": [
            [
                1],
            [
                2],
            [3,
                4],
            [],
            []
        ]
    }]
}

=== ramonmeza/conversation_editor/data/conversation_example.json
{
    "name": "Conversation Name",
    "description": "Description of the conversation",
    "nodes": [{
        "speaker": "Doctor",
        "text": "Hey there, how can I help you?"
    }, {
        "speaker": "Player",
        "text": "I'm not feeling too great. Can you take a look at me?"
    }, {
        "operator": "==",
        "attribute": "Health",
        "value": 100
    }, {
        "speaker": "Doctor",
        "text": "Doesn't seem like you have any wounds on you. What are your symptoms?"
    }, {
        "speaker": "Doctor",
        "text": "Well here's your problem! You're missing a leg!"
    }],
    "connections": [
        [1],
        [2],
        [3, 4],
        [],
        []
    ]
}
